"""twin_initial -- digital twin tables (DIGITAL_TWIN_README.md section 6)

Hand-written rather than autogenerated so it is reviewable and so it does not
depend on the host app's ``migrations/env.py`` having imported the twin models.

Cross-database (C2): no PostGIS, no dialect-specific types. JSON columns use
``sa.JSON``, which maps to native ``JSON`` on SQLite 3.9+ and ``JSON`` on
PostgreSQL. Timestamps use ``DateTime(timezone=True)``; the application layer
normalises to UTC via ``twin.models.UTCDateTime`` so SQLite's lack of tz
storage cannot produce a naive/aware split (C8).

``down_revision`` is deliberately left as ``None`` here. The instruction this
file shipped with was to chain it onto ``flask db heads``, but this repo has
no single head: all ten of its existing revisions declare
``down_revision = None`` too, so Alembic already sees ten independent heads
and ``flask db upgrade`` cannot run against this tree as it stands. The
application provisions its schema with ``db.create_all()`` instead (there is
no ``alembic_version`` row in ``instance/site.db``), and ``app.py`` calls that
after registering the twin, so the twin's tables are created the same way
every other table here is.

Chaining this one revision onto an arbitrary sibling would not fix that and
would make the twin the only migration in the repo pretending to a history
the rest does not have. If the migration history is ever repaired, set
``down_revision`` to whatever becomes the real head at that point; the
``upgrade()``/``downgrade()`` pair below is correct either way and has been
round-tripped against SQLite.
"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "twin_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        "twin_city",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=False),
        sa.Column("state", sa.String(length=128), nullable=True),
        sa.Column("country", sa.String(length=128), nullable=True),
        sa.Column("center_latitude", sa.Float(), nullable=False),
        sa.Column("center_longitude", sa.Float(), nullable=False),
        sa.Column("bbox_min_lon", sa.Float(), nullable=False),
        sa.Column("bbox_min_lat", sa.Float(), nullable=False),
        sa.Column("bbox_max_lon", sa.Float(), nullable=False),
        sa.Column("bbox_max_lat", sa.Float(), nullable=False),
        sa.Column("default_zoom", sa.Float(), nullable=True),
        sa.Column("default_pitch", sa.Float(), nullable=True),
        sa.Column("default_bearing", sa.Float(), nullable=True),
        sa.Column("zone_scheme", sa.String(length=32), nullable=True),
        sa.Column("h3_resolution", sa.Integer(), nullable=False),
        sa.Column("basin_name", sa.String(length=64), nullable=True),
        sa.Column("basin_outlet_lat", sa.Float(), nullable=True),
        sa.Column("basin_outlet_lon", sa.Float(), nullable=True),
        sa.Column("discharge_2yr_return", sa.Float(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_index("ix_twin_city_slug", "twin_city", ["slug"])

    op.create_table(
        "twin_zone",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("city_id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=False),
        sa.Column("zone_type", sa.String(length=16), nullable=False),
        sa.Column("parent_zone_id", sa.Integer(), nullable=True),
        sa.Column("center_latitude", sa.Float(), nullable=True),
        sa.Column("center_longitude", sa.Float(), nullable=True),
        sa.Column("boundary_geojson", sa.Text(), nullable=True),
        sa.Column("boundary_source", sa.String(length=24), nullable=True),
        sa.Column("population_estimate", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["city_id"], ["twin_city.id"],
                                name="fk_twin_zone_city"),
        sa.ForeignKeyConstraint(["parent_zone_id"], ["twin_zone.id"],
                                name="fk_twin_zone_parent"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("city_id", "slug", name="uq_twin_zone_city_slug"),
    )
    op.create_index("ix_twin_zone_city_id", "twin_zone", ["city_id"])

    op.create_table(
        "twin_cell",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("h3_index", sa.String(length=20), nullable=False),
        sa.Column("city_id", sa.Integer(), nullable=False),
        sa.Column("zone_id", sa.Integer(), nullable=True),
        sa.Column("center_latitude", sa.Float(), nullable=False),
        sa.Column("center_longitude", sa.Float(), nullable=False),
        sa.Column("boundary_geojson", sa.Text(), nullable=True),
        sa.Column("area_sqkm", sa.Float(), nullable=True),
        sa.Column("elevation_m", sa.Float(), nullable=True),
        sa.Column("elevation_source", sa.String(length=24), nullable=True),
        sa.Column("dist_to_water_m", sa.Float(), nullable=True),
        sa.Column("drain_length_m", sa.Float(), nullable=False),
        sa.Column("infra_criticality_cached", sa.Float(), nullable=False),
        sa.Column("terrain_score_cached", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["city_id"], ["twin_city.id"],
                                name="fk_twin_cell_city"),
        sa.ForeignKeyConstraint(["zone_id"], ["twin_zone.id"],
                                name="fk_twin_cell_zone"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("h3_index"),
    )
    op.create_index("ix_twin_cell_h3_index", "twin_cell", ["h3_index"])
    op.create_index("ix_twin_cell_city_id", "twin_cell", ["city_id"])
    op.create_index("ix_twin_cell_zone_id", "twin_cell", ["zone_id"])

    op.create_table(
        "twin_cell_state",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cell_id", sa.Integer(), nullable=False),
        sa.Column("horizon_hours", sa.Integer(), nullable=False),
        sa.Column("risk_score", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("hazard_score", sa.Float(), nullable=True),
        sa.Column("vulnerability_multiplier", sa.Float(), nullable=True),
        sa.Column("hydro_score", sa.Float(), nullable=True),
        sa.Column("incident_score", sa.Float(), nullable=True),
        sa.Column("terrain_score", sa.Float(), nullable=True),
        sa.Column("infra_score", sa.Float(), nullable=True),
        sa.Column("env_score", sa.Float(), nullable=True),
        sa.Column("raw_inputs", sa.JSON(), nullable=True),
        sa.Column("degraded_inputs", sa.JSON(), nullable=True),
        sa.Column("incident_count", sa.Integer(), nullable=False),
        sa.Column("top_incident_report_id", sa.Integer(), nullable=True),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["cell_id"], ["twin_cell.id"],
                                name="fk_twin_state_cell"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cell_id", "horizon_hours",
                            name="uq_twin_state_cell_horizon"),
    )
    op.create_index("ix_twin_cell_state_cell_id", "twin_cell_state", ["cell_id"])
    op.create_index("ix_twin_cell_state_horizon_hours", "twin_cell_state",
                    ["horizon_hours"])
    op.create_index("ix_twin_cell_state_computed_at", "twin_cell_state",
                    ["computed_at"])
    op.create_index("ix_twin_state_cell_horizon", "twin_cell_state",
                    ["cell_id", "horizon_hours"])

    op.create_table(
        "twin_cell_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cell_id", sa.Integer(), nullable=False),
        sa.Column("horizon_hours", sa.Integer(), nullable=False),
        sa.Column("risk_score", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["cell_id"], ["twin_cell.id"],
                                name="fk_twin_history_cell"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_twin_cell_history_cell_id", "twin_cell_history", ["cell_id"])
    op.create_index("ix_twin_cell_history_computed_at", "twin_cell_history",
                    ["computed_at"])
    op.create_index("ix_twin_history_cell_time", "twin_cell_history",
                    ["cell_id", "computed_at"])

    op.create_table(
        "twin_infrastructure",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("city_id", sa.Integer(), nullable=False),
        sa.Column("cell_id", sa.Integer(), nullable=True),
        sa.Column("osm_id", sa.String(length=48), nullable=True),
        sa.Column("asset_type", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("criticality", sa.Float(), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.Column("source", sa.String(length=24), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["city_id"], ["twin_city.id"],
                                name="fk_twin_infra_city"),
        sa.ForeignKeyConstraint(["cell_id"], ["twin_cell.id"],
                                name="fk_twin_infra_cell"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_twin_infrastructure_city_id", "twin_infrastructure",
                    ["city_id"])
    op.create_index("ix_twin_infrastructure_cell_id", "twin_infrastructure",
                    ["cell_id"])
    op.create_index("ix_twin_infrastructure_osm_id", "twin_infrastructure",
                    ["osm_id"])
    op.create_index("ix_twin_infra_city_type", "twin_infrastructure",
                    ["city_id", "asset_type"])

    op.create_table(
        "twin_data_snapshot",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_key", sa.String(length=64), nullable=False),
        sa.Column("city_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("records_ingested", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("payload_digest", sa.String(length=64), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["city_id"], ["twin_city.id"],
                                name="fk_twin_snapshot_city"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_twin_data_snapshot_source_key", "twin_data_snapshot",
                    ["source_key"])
    op.create_index("ix_twin_data_snapshot_city_id", "twin_data_snapshot",
                    ["city_id"])
    op.create_index("ix_twin_data_snapshot_started_at", "twin_data_snapshot",
                    ["started_at"])
    op.create_index("ix_twin_snapshot_source_time", "twin_data_snapshot",
                    ["source_key", "started_at"])


def downgrade():
    op.drop_table("twin_data_snapshot")
    op.drop_table("twin_infrastructure")
    op.drop_table("twin_cell_history")
    op.drop_table("twin_cell_state")
    op.drop_table("twin_cell")
    op.drop_table("twin_zone")
    op.drop_table("twin_city")
